version: "3.5"

services:
    heihei:
        image: tkpdx01/heihei:latest
        container_name: heihei
        # 自动重启
        restart: always
        network_mode: bridge
        # 挂载目录
        volumes:
            - /opt/xuexi/user:/xuexi/user
            #- /opt/xuexi/static:/xuexi/static
            #- /opt/xuexi/pdlearn:/xuexi/pdlearn
        # 打开的端口
        ports:
            # 打开30080端口，访问 http://服务器ip:30080 进行控制
            # 这个30081端口对应容器内8088是微信公众号控制端口，我预先映射出来了，免得你们再去查找
            - 30080:80
            - 30081:8088
        # 设置共享内存2g（shared memory）,减少chrome崩溃
        shm_size: 4gb
        # 环境变量
        environment:
            # 将在每天5：47和13：47及21：47自动运行一次学习，防止忘记点UID开始学习
            - CRONTIME=47 5,13,21 * * *
            # 打开专项答题
            - ZhuanXiang=True
            # 信息推送模式：网页模式
            - Pushmode=1
            # 以下爱参数网页模式不需要，其他模式请根据实际情况修改
            # - "AccessToken={token}"
            # - "Secret={密钥}"
            - AccessToken=63a66124219c8e4ad3e4bc4a9af68cf3ba9da242935d5b4661dc564c304d3517
            - Secret=SEC4720831bdb324c6d5ed20d6b7f815bbbacb0a4098eccab4dcb88a5854d2b9180
            - Scheme=dtxuexi://appclient/page/study_feeds?url=